### ISSUE TITLE
Unable to build (wrong type for Flush method)

### ISSUE THREAD

**Issue by Night1** [jmhodges/howsmyssl#195] opened 2017-11-21 11:41 UTC
Hey,

I keep getting this error when trying to build this application

```
./howsmyssl.go:146: cannot use client.Logger(*allowLogName) (type *"cloud.google.com/go/logging".Logger) as type logClient in assignment:
        *"cloud.google.com/go/logging".Logger does not implement logClient (wrong type for Flush method)
                have Flush() error
                want Flush()
```
Any ideas of why

**Comment by jmhodges** [comment] 2017-11-21 17:26
Sounds like your build system is ignoring the vendored cloud.google.com/go/logging depedency or you updated it accidentally? Can't reproduce locally.

**Comment by jmhodges** [comment] 2017-11-21 17:27
I'm going to close this because I'm pretty sure it's a local problem, but comment and lmk if it's not.

**Closed by jmhodges** 2017-11-21 17:27 UTC

**Comment by Night1** [comment] 2017-11-22 00:03
Hey, I tried this on two systems both running Ubuntu 17.10 upgraded from 17.04, same issue, with go 1.8.3
go version go1.8.3 linux/amd64 on both systems. 


I had to use go get -v cloud.google.com/go/logging since i got a missing error prior to that along with some other.

**Comment by Night1** [comment] 2017-11-24 14:57
Hey @jmhodges  I have now also testet on a clean centos build still same error presist.

**Comment by jmhodges** [comment] 2017-11-26 01:44
Are you sure you're using the latest code and haven't deleten parts of the vendor directory (or forgotten to copy it?)

**Comment by Night1** [comment] 2017-11-26 14:19
@jmhodges  Hey, I did a git clone from your repo so everything there should be in that, I have acquired the missing go modules with commands as stated,

**Comment by jmhodges** [comment] 2017-11-27 21:52
Yeah, no, you seem to be cloning from an old commit or building without copying the right files. I just tested this myself (on go 1.9):

```
$  export GOPATH=/Users/jmhodges/projects/gotmp
$  mkdir {src,pkg}
$  go get -d github.com/jmhodges/howsmyssl
$  cd src/github.com/jmhodges/howsmyssl/
$  go build .
$  ./howsmyssl
2017/11/27 13:49:55 Booting HTTPS on localhost:10443 and HTTP on localhost:10080
```

**Comment by jmhodges** [comment] 2017-11-27 21:53
(And `ls /Users/jmhodges/projects/gotmp/src` returns only `github.com` and `ls /Users/jmhodges/projects/gotmp/src/github.com` returns only `jmhodges`)

**Comment by Night1** [comment] 2017-11-27 22:09
Still same issue, 

`allow.go:16:2: cannot find package "cloud.google.com/go/logging" in any of:
        /usr/lib/go-1.8/src/cloud.google.com/go/logging (from $GOROOT)
        /Users/jmhodges/projects/gotmp/src/cloud.google.com/go/logging (from $GOPATH)
allow.go:18:2: cannot find package "github.com/dgryski/go-topk" in any of:
        /usr/lib/go-1.8/src/github.com/dgryski/go-topk (from $GOROOT)
        /Users/jmhodges/projects/gotmp/src/github.com/dgryski/go-topk (from $GOPATH)
howsmyssl.go:30:2: cannot find package "golang.org/x/net/context" in any of:
        /usr/lib/go-1.8/src/golang.org/x/net/context (from $GOROOT)
        /Users/jmhodges/projects/gotmp/src/golang.org/x/net/context (from $GOPATH)
allow.go:19:2: cannot find package "golang.org/x/net/publicsuffix" in any of:
        /usr/lib/go-1.8/src/golang.org/x/net/publicsuffix (from $GOROOT)
        /Users/jmhodges/projects/gotmp/src/golang.org/x/net/publicsuffix (from $GOPATH)
allow.go:20:2: cannot find package "golang.org/x/oauth2/google" in any of:
        /usr/lib/go-1.8/src/golang.org/x/oauth2/google (from $GOROOT)
        /Users/jmhodges/projects/gotmp/src/golang.org/x/oauth2/google (from $GOPATH)
allow.go:21:2: cannot find package "golang.org/x/oauth2/jwt" in any of:
        /usr/lib/go-1.8/src/golang.org/x/oauth2/jwt (from $GOROOT)
        /Users/jmhodges/projects/gotmp/src/golang.org/x/oauth2/jwt (from $GOPATH)
howsmyssl.go:31:2: cannot find package "google.golang.org/api/option" in any of:
        /usr/lib/go-1.8/src/google.golang.org/api/option (from $GOROOT)
        /Users/jmhodges/projects/gotmp/src/google.golang.org/api/option (from $GOPATH)

		`
		

Then after running 
		go get github.com/dgryski/go-topk
		go get golang.org/x/net/context
		go get golang.org/x/net/publicsuffix
		go get google.golang.org/api/option
		go get golang.org/x/oauth2/jwt
		go get golang.org/x/oauth2/google

go build still runs with this error again

		
		# _/home/night/go/src/github.com/jmhodges/howsmyssl
./howsmyssl.go:146: cannot use client.Logger(*allowLogName) (type *"cloud.google.com/go/logging".Logger) as type logClient in assignment:
        *"cloud.google.com/go/logging".Logger does not implement logClient (wrong type for Flush method)
                have Flush() error
                want Flush()`



I also tried same package on a windows machine and it ran without issues.

**Comment by jmhodges** [comment] 2017-11-27 22:24
If it worked on the windows machine, it definitely seems like the problem is in your environment on that machine. You've not provided the steps you made to repro this, so I think you're going to have to work this out yourself. The problem is with your machine, not the repo.

**Comment by jmhodges** [comment] 2018-04-28 01:01
From another ticket, I bet I figured out what you misconfigured. You've cloned howsmyssl outside of your GOPATH and so the vendor dir is not being used. Move it to $GOPATH/src/github.com/jmhodges/howsmyssl (or do a go get github.com/jmhodges/howsmyssl) and build it from there
